EXIT_REASON_EVENT_REASON_MAP = {
    "8": "INVOLUNTBEHISSUES",
    "12": "INVOLUNTREDUCTION",
    "10": "INVOLUNTPERFISSUE",
    "17": "TERMDONOTUSE",
    "14": "RETIREMENT",
    "15": "TERINTCOM",
    "16": "TERMNeutral",
    "18": "VOLUNTPERSONALREASONS",
    "4": "VOLUNTREMUNERATION",
    "7": "FULLTIMEEDU",
    "2": "VOLUNTDEVOPP",
    "3": "VOLUNTMNGCOLLEAGUE",
    "1": "VOLUNTCOMPCULTURE",
    "5": "VOLUNTBALANCE",
    "6": "VOLUNTWORKLOCATION"
    }